CREATE TABLE IF NOT EXISTS countries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  capital VARCHAR(150) DEFAULT NULL,
  region VARCHAR(100) DEFAULT NULL,
  population BIGINT NOT NULL DEFAULT 0,
  currency_code VARCHAR(10) NOT NULL DEFAULT 'UNKNOWN',
  exchange_rate DOUBLE NOT NULL DEFAULT 0,
  estimated_gdp DOUBLE DEFAULT 0,
  flag_url VARCHAR(255) DEFAULT NULL,
  last_refreshed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_name (name)
);
